name: geofancing
description: Application Geofancing

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  image_picker:
  flutter:
    sdk: flutter
  rxdart: ^0.23.1
  json_annotation: ^2.0.0
  shared_preferences: ^0.5.3+1
  url_launcher: ^5.0.3
  dio: ^3.0.9
  flutter_html: ^0.11.0
  carousel_slider: ^1.3.1
  rflutter_alert: ^1.0.2
  location: ^2.3.5
  google_maps_flutter: ^0.5.28+1
  latlong: ^0.6.1
  cached_network_image: ^2.0.0
  flutter_custom_clippers: ^1.1.0
  dotted_border: ^1.0.5
  camera: ^0.5.8+2
  path: ^1.6.4
  path_provider: ^1.6.11
  intl: ^0.16.1
  shimmer: ^1.0.1
  #  permission: ^0.1.7
  #

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  lite_rolling_switch: ^0.1.1

  package_info: ^0.4.0+14

  provider:
  #languange
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  flutter_launcher_icons: ^0.7.4


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/logo_ramayana.png
    - assets/images/bg_header.png
    - assets/images/bg_header.jpg
    - assets/icons/icons_call.png
    - assets/icons/icons_filter.png
    - assets/icons/icons_card.png
    - assets/icons/icons_manfaat.png
    - assets/icons/icons_peserta.png
    - assets/icons/icons_provider.png
    - assets/icons/icons_riwayat.png
    - assets/icons/icons_exit.png
    - assets/icons/icon_car.png
    - assets/icons/car_icon.png
    - assets/icons/icons_syaratketentuan.png
    - assets/icons/icons_resetpassword.png
    - assets/icons/icons_gantiakun.png
    - assets/icons/ic_mail.png
    - assets/icons/ic_history_klaim.png
    - assets/icons/ic_notifi.png
    - assets/icons/ic_calender.png
    - assets/icons/ic_camera.png
    - assets/icons/icon_book.png
    - assets/icons/icon_language.png
    - assets/icons/icon_about.png
    - assets/images/not_found.png
    - assets/icons/ic_benefit.png
    - assets/icons/icon_settings.png
    - assets/images/kartu_asuransi.png
    - assets/images/no_image_available.jpg
    - assets/images/ic_date.png
    - assets/images/ic_sorting.png
    - assets/images/ic_family.png
    - assets/icons/close_popup.png
    - assets/icons/icons_chat.png
    - assets/images/icon_toyoga.png
    - assets/images/icon_toyoga_t.png

  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages